# Generated by Django 4.1.7 on 2023-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="position",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="option",
            unique_together={("position", "id")},
        ),
    ]
