# Generated by Django 4.1.7 on 2023-11-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_option_unique_together_alter_question_text_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={"ordering": ["position"]},
        ),
    ]
